const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx={window:{}};vm.createContext(ctx);
for(const f of ['img','dex-filter'])vm.runInContext(fs.readFileSync('lib/'+f+'.js','utf8'),ctx);
const F=ctx.window.AtelierDexFilter,st=require('./dex-filter-fixture.cjs');
const select=f=>F.select(st,f),files=f=>Array.from(select(f),r=>r.file);
assert.equal(select({}).length,4,'default roster includes missing art');
assert.equal(select({q:'#0001'}).length,1,'number search must not match 1001');
assert.equal(select({q:'alpha'})[0].card.name,'A');
assert.equal(select({type:'flying'})[0].card.name,'A','secondary type must match');
assert.equal(select({gen:'2',type:'water'})[0].card.name,'B');
assert.equal(select({gen:'2',type:'flying'}).length,0,'filters must intersect');
assert.deepEqual(files({style:'glossy_promo',cut:'portrait',form:'heavy'}),[],'no style fallback');
assert.deepEqual(files({style:'game_keyart',cut:'portrait',form:'heavy'}),['a-heavy.webp']);
assert.deepEqual(files({cut:'portrait',form:'heavy_overdrive'}),['a-heavy-od.webp']);
assert.deepEqual(files({cut:'portrait',form:'overdrive'}),['b-old-od.webp']);
assert.deepEqual(files({style:'game_keyart',cut:'action',form:'heavy'}),['a-heavy-act1.webp','a-heavy-act2.webp']);
assert.deepEqual(files({style:'glossy_promo',cut:'casual',form:'heavy'}),['a-gloss-casual.webp'],'casual ignores stale form');
assert.deepEqual(files({cut:'base'}),['a-base.webp','d-legacy.webp']);
assert.deepEqual(files({cut:'extra'}),['a-extra.webp']);
assert.equal(files({style:'game_keyart',cut:'all',form:'heavy'}).length,3);
assert.equal(files({style:'game_keyart',cut:'casual'}).length,3);
assert.equal(select({style:'mecha_cinematic_keyart'}).length,0,'empty style does not show unregistered cards');
assert.equal(select({form:'mobility'}).length,0,'missing requested form must not use another cut');
assert.equal(select({style:'game_keyart'})[1].file,'b-old-od.webp');
assert.deepEqual(JSON.parse(JSON.stringify(F.normalize({cut:'BAD',gen:'99',style:'BAD',type:'BAD',form:'BAD',q:4},st))),JSON.parse(JSON.stringify(F.defaults())));
const real=JSON.parse(fs.readFileSync('data/card.json','utf8'));
const realState={cards:Object.values(real.cards).flat(),defs:real.forms,img:JSON.parse(fs.readFileSync('data/img.json','utf8')).img,styleName:Object.fromEntries(JSON.parse(fs.readFileSync('data/style.json','utf8')).styles.map(s=>[s.key,s.name]))};
assert.equal(F.select(realState,{}).length,1025);
for(const r of F.select(realState,{cut:'all'}))assert(r.file&&r.card&&r.cut!=='auto');
console.log('PASS dex filters: combined metadata, secondary type, exact artwork, all cuts, empty results, legacy data and 1025-card roster');
