/* 낱말 표 — 화면에 뜨는 주제 낱말은 전부 여기 한 곳에서 온다.

   앞선 저장소(atelier)에서 주제를 갈아 끼워 본 기록(TRY_SAMGUK.md)이 남긴 교훈이다.
   규칙 코드는 한 줄도 안 고쳐도 돌았는데, "기체" 69 · "파일럿" 43 · "지휘관" 25 ·
   "모함" 8 … 합쳐 190 자리의 사람이 읽는 말이 화면에 박혀 있어서 다른 주제로
   돌리면 "모함 건업", "기동전사 드래프트" 같은 것이 떴다.

   그래서 이 저장소는 처음부터 말을 코드에 안 적는다. 화면은 W('kind.unit') 로
   부르고, 주제를 바꾸면 이 파일 하나만 갈아 끼운다.

   쓰는 법
     W('kind.unit')                 → '유닛'
     W('kind.unit', {n: 3})         → 자리표시자가 있으면 채워 넣는다
     W('없는.열쇠')                  → 열쇠를 그대로 돌려주고 콘솔에 적는다
                                       (조용히 빈칸이 되는 것보다 낫다)  */
(function (root) {
  'use strict';

  /* 주제를 정하면 이 표만 고친다. 값이 비어 있는 것은 아직 안 정했다는 뜻이다. */
 var WORDS = {
    "nav.survey": "탐사",
    "home.survey.code": "05 / EXPEDITION",
    "home.survey.title": "탐사 작전",
    "home.survey.note": "대원 여섯, 세 탐사 구역, 주어진 시간은 6일. 적성과 에너지를 읽고 최선의 배치를 찾으세요.",
    "survey.title": "탐사 작전",
    "survey.eyebrow": "FIELD OPERATIONS / 06 DAYS",
    "survey.headline": "오늘은 누구를 보낼까.",
    "survey.intro": "타입과 장갑을 맞춰 구역을 조사하세요. 쉬는 대원은 다음 탐사를 준비합니다.",
    "survey.start": "작전 시작",
    "survey.daily": "오늘의 작전",
    "survey.random": "새 무작위 작전",
    "survey.replay": "같은 작전 재도전",
    "survey.daily.note": "오늘은 같은 대원·같은 구역으로 도전합니다. 새로고침해도 이어집니다.",
    "survey.seed": "작전 코드 {seed}",
    "survey.day": "{n}일차 / {total}일",
    "survey.phase.plan": "배치 중",
    "survey.phase.report": "복귀 보고",
    "survey.phase.finished": "작전 종료",
    "survey.score": "탐사 메달",
    "survey.goal": "목표 {n}개",
    "survey.kits": "정비 키트",
    "survey.best": "내 최고 기록 {n}개",
    "survey.routes": "오늘의 탐사 구역",
    "survey.routes.note": "한 구역에 두 명까지. 예상 메달은 배치 즉시 계산됩니다.",
    "survey.route": "구역 {n}",
    "survey.empty": "대원을 배치해 주세요",
    "survey.slot": "{n} / 2명",
    "survey.power": "탐사력",
    "survey.demand": "필요 {n}",
    "survey.threshold": "★ {one} · ★★ {two} · ★★★ {three}",
    "survey.grade.0": "미달",
    "survey.grade.1": "부분 조사",
    "survey.grade.2": "완료",
    "survey.grade.3": "완벽 조사",
    "survey.affinity": "적성 타입 +3",
    "survey.synergy": "같은 알그룹 · 협업 +2",
    "survey.energy": "에너지",
    "survey.cost": "소모 {n}",
    "survey.crew": "탐사 대원",
    "survey.crew.note": "배치와 폼을 고른 뒤 출발하세요. 배치하지 않은 대원은 에너지가 3 회복됩니다.",
    "survey.assignment": "배치 구역",
    "survey.rest": "기지에서 휴식",
    "survey.rest.short": "휴식",
    "survey.base": "기본 적성",
    "survey.repair": "정비 +3",
    "survey.repair.label": "{name} 정비 · 키트 1개로 에너지 3 회복",
    "survey.form.label": "{name} · {form} · 에너지 {n} 소모",
    "survey.assignment.label": "{name} 배치 구역",
    "survey.form.light": "효율 운용 · 소모 2",
    "survey.form.heavy": "회수 강화 · 소모 3",
    "survey.form.mobility": "구조 강화 · 소모 3",
    "survey.forecast": "예상 +{n} 메달",
    "survey.assigned": "{n}명 출발 · {rest}명 휴식",
    "survey.launch": "탐사 출발",
    "survey.allrest": "전원 휴식으로 하루 보내기",
    "survey.clear": "배치 비우기",
    "survey.review": "복귀 보고",
    "survey.earned": "오늘 +{n} 메달",
    "survey.next": "다음 날 준비",
    "survey.reward.note": "하나를 고르면 다음 날로 넘어갑니다. 장비 강화는 이번 작전이 끝날 때까지 유지됩니다.",
    "survey.reward.restock": "정비 키트 +2",
    "survey.reward.restock.note": "원하는 대원의 에너지를 회복하세요.",
    "survey.reward.research": "분석 장비 강화",
    "survey.reward.research.note": "전 대원 조사 적성 +1",
    "survey.reward.salvage": "회수 장비 강화",
    "survey.reward.salvage.note": "전 대원 회수 적성 +1",
    "survey.reward.rescue": "구조 장비 강화",
    "survey.reward.rescue.note": "전 대원 구조 적성 +1",
    "survey.upgrades": "장비 강화",
    "survey.history": "지난 탐사 기록",
    "survey.history.day": "{n}일차 · +{score} 메달",
    "survey.finish.win": "목표를 달성했습니다!",
    "survey.finish.loss": "다음 작전은 더 멀리.",
    "survey.finish.note": "6일 동안 모은 메달 {score}개 · 목표 {goal}개",
    "survey.rank": "작전 평가",
    "survey.rank.S": "빈틈없는 관제",
    "survey.rank.A": "탐사 전문가",
    "survey.rank.B": "성장하는 지휘관",
    "survey.rank.C": "새로운 시작",
    "survey.new": "다른 작전",
    "survey.confirm": "지금 작전을 마치고 새로 시작할까요?",
    "survey.cancel": "계속하기",
    "survey.rules": "탐사 안내",
    "survey.rule.1": "6일 동안 탐사 메달 30개가 목표입니다. 출발 전 보이는 예상 결과가 그대로 적용됩니다.",
    "survey.rule.2": "조사·회수·구조 적성은 현재 도감의 종족값 분포에서 만듭니다. 총합 대신 각 대원의 강점을 살렸습니다.",
    "survey.rule.3": "구역에 맞는 타입이면 탐사력 +3. 같은 알그룹인 두 대원이 함께 가면 협업 +2를 받습니다.",
    "survey.rule.4": "경장은 에너지 2, 중장·고기동은 3을 씁니다. 중장은 회수에, 고기동은 구조에 유리합니다. 쉬면 +3, 정비 키트 하나로도 +3 회복합니다.",
    "survey.rule.5": "탐사력 60%는 메달 1개, 100%는 2개, 130%는 3개입니다. 복귀 때 키트 보급이나 이번 작전의 장비 강화 하나를 고르세요.",
    "survey.saved": "이 브라우저에 자동 저장됩니다.",
    "survey.storage.failed": "저장이 막혀 있습니다. 이 창에서는 계속 플레이할 수 있습니다.",
    "survey.load": "탐사 데이터를 준비하는 중…",
    "survey.retry": "다시 불러오기",
    "survey.corrupt": "이전 저장을 읽을 수 없어 새 작전을 준비했습니다.",
    "survey.error.full": "이 구역은 두 명이 이미 배치되어 있습니다.",
    "survey.error.tired": "에너지가 부족합니다. 정비하거나 휴식시켜 주세요.",
    "survey.error.kits": "정비 키트가 없습니다.",
    "survey.error.fullEnergy": "이미 에너지가 가득합니다.",
    "survey.error.form": "사용할 수 없는 폼입니다.",
    "survey.error.mission": "구역을 다시 선택해 주세요.",
    "survey.error.member": "대원을 다시 선택해 주세요.",
    "survey.error.phase": "이미 처리된 선택입니다.",
    "survey.error.action": "선택을 다시 확인해 주세요.",
    "survey.error.data": "도감 데이터를 불러오지 못했습니다.",
    "survey.skill.research": "조사",
    "survey.skill.salvage": "회수",
    "survey.skill.rescue": "구조",
    "survey.biome.forest": "수풀 관측지",
    "survey.biome.coast": "해안 관측소",
    "survey.biome.volcano": "화산 지열대",
    "survey.biome.ruins": "고대 유적",
    "survey.biome.city": "폐쇄 발전소",
    "survey.biome.canyon": "협곡 전초기지",
    "survey.biome.night": "밤안개 습지",
    "survey.biome.meadow": "꽃바람 평원",
    "workspace.signature": "CREATURE DESIGN LAB",
    "dex.title": "포켓몬 메카 도감",
    "home.title": "익숙한 포켓몬, 새로운 가능성.",
    "home.intro": "원본의 개성에서 시작해 나만의 메카 캐릭터를 만드세요. 도감에 모인 모습들을 비교하고, 같은 인물의 다음 폼과 장면을 이어갈 수 있습니다.",
    "home.tag": "발견하고 · 만들고 · 기록하기",
    "home.dex.code": "01 / COLLECTION",
    "home.prompt.code": "02 / CREATION",
    "home.dex.title": "도감 둘러보기",
    "home.dex.note": "포켓몬의 정보와 완성된 폼, 액션과 일상 이미지를 한곳에서.",
    "home.prompt.title": "프롬프트 만들기",
    "home.prompt.note": "기준 인물부터 경장·중장·고기동·폭주, 그리고 새로운 일상까지.",
    "home.themes": "오늘의 연구소 분위기",
    "home.themes.note": "고른 테마는 도감과 생성기에도 함께 적용됩니다.",
    "theme.note.midnight": "별빛 아래의 탐사 기록",
    "theme.note.daylight": "몬스터볼 레드와 민트",
    "theme.note.blossom": "연분홍 꽃잎과 페어리 빛",
    "theme.note.moss": "짙은 녹음과 연두 새싹",
    "theme.note.plum": "보랏빛 안개 속 작은 유령",
    "theme.note.sand": "햇살 노랑과 전기 스파크",
    "theme.note.deep": "푸른 물결과 청록빛 산호",
    "theme.note.ember": "뜨거운 불꽃과 주황 잔광",
    "prompt.title": "프롬프트 스튜디오",
    "prompt.subtitle": "기준 인물을 만들고, 같은 인물의 폼과 장면을 확장합니다.",
    "prompt.portrait": "폼 초상",
    "prompt.action": "액션",
    "prompt.casual": "일상컷",
    "prompt.source": "원본 포켓몬",
    "prompt.type": "타입",
    "prompt.style": "화풍",
    "prompt.style.sample.title": "{style} · 예시 이미지",
    "prompt.style.sample.open": "{style} 예시 이미지 크게 보기 (새 탭)",
    "prompt.style.sample.alt": "{style} 화풍의 피카츄 여성 경장 기준 시트",
    "prompt.style.sample.settings": "피카츄 · 새 인물 만들기 · 경장 · Youthful · 나머지 AUTO",
    "prompt.style.sample.note": "화풍별로 새로 생성한 기준 시트입니다. 자동 설정에 따라 외형과 장비는 달라질 수 있습니다. 이미지를 누르면 크게 볼 수 있습니다.",
    "prompt.style.sample.loading": "예시 이미지를 불러오는 중입니다.",
    "prompt.style.sample.error": "예시 이미지를 불러오지 못했습니다. 잠시 후 다시 선택해 주세요.",
    "prompt.stage": "인물 기준",
    "prompt.create": "새 인물 만들기",
    "prompt.reference": "확정한 이미지 이어가기",
    "prompt.create.note": "이미지 첨부 없이 성인 여성 캐릭터를 새로 만듭니다. 포켓몬 원작 이미지도 필수가 아닙니다. 마음에 드는 결과를 확정한 뒤 후속 생성의 기준으로 사용하세요.",
    "prompt.reference.note": "이미지 생성 시 확정한 기준 이미지를 함께 첨부하세요. 얼굴·머리·체형은 그 이미지에서 유지하고, 표정과 움직임은 바꿀 수 있습니다.",
    "prompt.anchor.note": "후속 결과를 계속 새 기준으로 교체하지 말고, 처음 확정한 인물 이미지를 유지하세요. 기준 이미지 한 장이면 시작할 수 있습니다.",
    "prompt.form": "장갑 폼",
    "prompt.base": "폭주 기준 장갑",
    "prompt.base.reference": "첨부 이미지에 입고 있는 장갑",
    "prompt.light.note": "보디슈트 위 한 겹의 주 장갑. 노출량과는 별개입니다.",
    "prompt.heavy.note": "몸통·골반·허벅지와 보디슈트 윤곽은 기준 체형대로, 두꺼운 장갑은 몸 바깥의 프레임과 지지대로 분리합니다.",
    "prompt.mobility.note": "체형은 그대로, 얇은 외향 패널·후방 추진 구조와 빈 공간으로 경장과 다른 기동형 실루엣을 만듭니다.",
    "prompt.overdrive.note": "기존 패널 개방에 강한 원본 속성 에너지와 긴장된 자세를 더한 고출력 상태. 중장은 기존 두꺼운 패널을 크게 벌려 내부 구조를 드러냅니다. 초상 구도와 기준 장갑은 유지합니다.",
    "prompt.portrait.create.note": "기준 시트 한 장을 만듭니다. 정면·후면 전신과 오른쪽 확대컷 3개(얼굴·머리–어깨 설계·후면 장착부)를 가로폭을 넓힌 3:4 화면에 함께 배치합니다.",
    "prompt.portrait.note": "확정한 기준 인물의 전신 한 컷을 만듭니다. 기준 시트는 정면 모습을 바탕으로 하며, 폼끼리 비교할 수 있게 2:3 구도와 카메라를 유지합니다.",
    "prompt.action.note": "선택한 폼으로 움직임·시점·배경을 자유롭게 연출합니다. 화풍은 그대로 유지합니다.",
    "prompt.casual.note": "확정한 인물의 새로운 일상 장면. 폼 설정은 적용되지 않습니다.",
    "prompt.motifs": "살릴 원본 특징 — 선택 보정",
    "prompt.motifs.ph": "비워 두면 수집된 원작 외형을 자동 사용합니다",
    "prompt.help.motifs.auto": "입력하지 않아도 됩니다. 새 인물은 선택한 포켓몬의 외형 데이터를 자동으로 사용하며, 입력하면 그 문구를 우선합니다. 이어가기는 승인 이미지의 실제 디자인을 따릅니다.",
    "prompt.appearance.data.failed": "외형 데이터를 불러오지 못했습니다. 현재는 포켓몬 이름 기반으로 생성합니다. 새로고침하면 다시 시도합니다.",
    "prompt.appearance.source": "외형 출처: Bulbapedia",
    "prompt.appearance.license": "CC BY-NC-SA 2.5 · 추출·축약",
    "prompt.insets.title": "기준 시트 확대컷 세 칸",
    "prompt.insets.note": "얼굴은 인물을, 머리–어깨 3/4 확대는 장갑 설계 언어와 머리 장비 하드포인트를, 후면 확대는 등딱지·꼬리 같은 영구 장비의 장착점을 담습니다. 후면 칸은 원작 외형 자료에서 뿌리 있는 부위만 자동으로 채웁니다. 별도 입력은 필요 없습니다.",
    "prompt.insets.reset": "보정 지우고 자동 사용",
    "prompt.insets.advanced": "확대컷 직접 보정 — 선택",
    "prompt.insets.face": "1. 얼굴 정체성",
    "prompt.insets.face.help": "눈 색과 형태, 헤어, 턱선을 한 얼굴 확대컷에서 확인합니다.",
    "prompt.insets.design": "2. 머리–어깨 설계 언어",
    "prompt.insets.design.help": "한쪽 관자놀이에서 어깨까지 3/4 확대. 머리 장비 하드포인트와 대표 어깨판의 패널 분할·테두리·체결·발광선을 보여 줍니다. 다른 폼은 이 문법만 따르고 크기·층수는 폼이 정합니다.",
    "prompt.insets.mount": "3. 후면 장착부",
    "prompt.insets.mount.help": "등딱지·꼬리·구근처럼 모든 폼에 남는 장비가 몸에 붙는 뿌리. 장비가 없는 종은 등과 목 칼라의 하네스 고정점을 보여 줍니다.",
    "prompt.head": "머리 특징 표현",
    "prompt.head.help": "원본의 귀·뿔·볏·잎 같은 머리 특징을 경장 인물의 머리에 어떻게 옮길지 정합니다. 헬멧은 여기서 고르지 않습니다. 중장은 얼굴 개방형 헬멧, 고기동은 센서 핀으로 폼이 정합니다.",
    "prompt.override": "폼 세부 요청",
    "prompt.override.ph": "예: 왼쪽 어깨 패널만 개방",
    "prompt.appearance": "최초 인물 외형",
    "prompt.figure.pick": "{label} · 이미지로 선택",
    "prompt.color.pick": "{label} 팔레트",
    "prompt.eye.same": "양쪽 같은 색",
    "prompt.appearance.note": "자동 항목은 모델이 결정합니다. 기준 이미지 모드에서는 이 값들을 다시 적용하지 않습니다.",
    "prompt.group.base": "기본",
    "prompt.group.build": "체형",
    "prompt.group.face": "얼굴",
    "prompt.group.hair": "머리",
    "prompt.auto": "자동",
    "prompt.custom": "직접 입력",
    "prompt.lock": "무작위 변경 잠금",
    "prompt.unlock": "잠금 해제",
    "prompt.random": "외형 무작위",
    "prompt.reset": "외형 초기화",
    "prompt.scene.settings": "장면 설정",
    "prompt.scene.random.short": "랜덤",
    "prompt.scene.random.field": "{label} 랜덤 선택",
    "prompt.scene.random.all": "잠기지 않은 항목 전체 랜덤",
    "prompt.scene.lock": "잠금",
    "prompt.scene.locked": "잠김",
    "prompt.scene.lock.field": "{label} 랜덤 잠금",
    "prompt.scene.unlock.field": "{label} 랜덤 잠금 해제",
    "prompt.scene.random.help": "각 선택 항목을 따로 뽑거나 전체를 한 번에 뽑을 수 있어요. 잠금은 랜덤 변경만 막으며 직접 선택은 가능해요. 예시를 잠그면 연결된 갈래도 랜덤에서 보호해요. 직접 입력한 문구와 인물·화풍·폼은 유지해요.",
    "prompt.expression": "표정",
    "prompt.pose": "자세",
    "prompt.orientation": "방향",
    "prompt.aspect": "화면 비율",
    "prompt.scene": "장소·상황",
    "prompt.outfit": "의상·소품",
    "prompt.frame": "프레이밍 · 담는 범위",
    "prompt.lens": "화각 · 렌즈 느낌",
    "prompt.camera": "카메라·구도 추가 지시",
    "prompt.help.expression": "표정의 분위기를 정해요. 자동이면 장면에 맞게 결정하며, 기준 인물의 얼굴은 유지해요.",
    "prompt.help.pose": "몸과 손의 동작을 정해요. 자동이면 장면 예시의 행동을 따르고, 직접 고른 포즈는 예시보다 우선해요.",
    "prompt.help.orientation": "카메라를 향한 몸의 방향이나 시점을 정해요. 포즈와 함께 자연스럽게 적용해요.",
    "prompt.help.frame": "인물을 머리부터 어디까지 보여줄지 정해요. 화각은 원근감, 이 메뉴는 담는 범위를 조절해요. 자동이면 장면에 맞춰 정해요.",
    "prompt.help.lens": "화각은 주변 공간이 보이는 범위예요. 같은 프레이밍에서는 광각일수록 앞뒤 거리감이 커지고, 망원일수록 배경이 가까이 겹쳐 보이는 느낌이에요. mm는 그림의 원근감을 설명하는 값이며, 화풍이나 배경 흐림을 자동으로 바꾸지는 않아요.",
    "prompt.help.aspect": "완성 이미지의 가로:세로 비율이에요. 담는 범위는 프레이밍에서 따로 정해요.",
    "prompt.help.camera": "선택한 프레이밍과 화각을 보완할 내용을 적어요. 예: 눈높이에서 촬영, 배경 흐림 약하게.",
    "prompt.help.example": "이 갈래에서 그리고 싶은 활동을 골라요. 자동이면 갈래에 맞는 장면을 정해요.",
    "prompt.help.example.custom": "누가 어디에서 무엇을 하는지, 손에 든 물건까지 적으면 장면이 더 구체적이 돼요.",
    "prompt.help.category.custom": "원하는 일상의 주제나 분위기를 적어요. 구체적인 행동은 장면 예시나 장소·상황에 덧붙일 수 있어요.",
    "prompt.help.scene": "시간·날씨·장소와 진행 중인 일을 덧붙여요. 비워 두면 선택한 갈래와 예시를 따라요.",
    "prompt.help.outfit": "이번 장면에서 입을 옷과 사용할 소품을 적어요. 기준 이미지의 얼굴·머리·체형은 그대로 유지해요.",
    "prompt.help.custom": "선택 메뉴로 표현하기 어려운 조명·분위기·세부 동작을 추가해요.",
    "prompt.help.motifs": "의상과 소품에 반영할 포켓몬의 색·무늬·특징을 적어요. 일상컷에 장갑을 자동으로 추가하지 않아요.",
    "prompt.extra": "추가 연출 요청",
    "prompt.category": "일상 갈래",
    "prompt.example": "장면 예시",
    "prompt.axes": "세부 강도",
    "prompt.action.settings": "액션 연출",
    "prompt.action.category": "액션 갈래",
    "prompt.action.example": "액션 장면 예시",
    "prompt.action.category.help": "전투·기동·구조·훈련 중 원하는 방향을 골라요. 자동이면 장소와 추가 요청에 맞춰 정해요.",
    "prompt.action.example.help": "이 갈래의 구체적인 동작을 골라요. 자동이면 갈래와 세부 설정에 맞게 구성해요.",
    "prompt.action.example.empty": "액션 갈래를 고르면 해당 장면 예시가 열려요. 장소·상황이나 추가 요청으로 직접 설명해도 돼요.",
    "prompt.action.pose.help": "전투·이동·구조에 맞는 몸과 손의 자세를 골라요. 선택한 포즈가 예시의 기본 자세보다 우선해요.",
    "prompt.copy": "프롬프트 복사",
    "prompt.copied": "복사했습니다.",
    "prompt.copy.failed": "자동 복사가 안 됩니다. 아래 글을 선택해 복사하세요.",
    "prompt.output": "생성된 프롬프트",
    "prompt.count": "{n}자",
    "prompt.gallery": "등록된 이미지",
    "prompt.gallery.note": "선택한 화풍·폼·모드의 등록 이미지입니다. 기준 이미지로 자동 지정되지는 않습니다.",
    "prompt.storage.failed": "이 브라우저에서는 설정을 저장하지 못했습니다. 현재 화면에서는 계속 사용할 수 있습니다.",
    "prompt.retry": "다시 읽기",
    "prompt.source.count": "{n}종",
    "prompt.local.note": "선택한 설정은 이 브라우저에 자동 저장됩니다.",
    "prompt.output.error": "설정을 확인해 주세요: {message}",
    /* 이 놀이 자체 */
    'app.title': '포켓몬 메카 연구소',
    'app.subtitle': '포켓몬의 개성을 기록하고, 새로운 메카 폼을 발견합니다.',
    'app.code': 'PKM / 001',
    'app.brand': 'POKÉMON × MECHA',   /* 큰 제목 위 작은 글씨. 저장소 이름이 아니라 만든 이의 표다 */

    /* 카드 갈래 — data/card.json 의 kinds 와 같이 고친다 */
    'kind.character': '캐릭터',

    /* 폼 — 장비 목록이 아니라 장갑을 몇 겹 겹쳤나로 가른다 */
    'form.light': '경장',
    'form.heavy': '중장',
    'form.mobility': '고기동',
    'form.overdrive': '폭주',
    'form.overdriveOf': '{form}-폭주',
    'form.all': '전체',
    'form.none': '폼 없음',

    /* 묶음 */
    'group.one': '타입',
    'group.all': '전체',
    'group.none': '소속 없음',

    /* 화면 공통 */
    'ui.search': '이름으로 검색',
    'ui.filter': '필터',
    'ui.reset': '조건 초기화',
    'ui.empty': '해당하는 것이 없다',
    'ui.loading': '읽는 중…',
    'ui.error': '자료를 못 읽었다 — {message}',

    /* 바탕 화면(index.html) — 놀이가 정해지면 통째로 지워도 되는 자리다 */
    'boot.layer': '공통 계층',
    'boot.next': '다음에 할 일',
    'boot.step1': '놀이를 정하고 lib/words.js 의 낱말 표부터 채운다.',
    'boot.step2': 'data/card.json 의 kinds 로 카드 갈래를 정한다.',
    'boot.step3': '그림을 쓸 때 lib/img.js 의 BASE 를 그림 저장소로 맞춘다.',

    /* 포켓몬 연구소 테마. 저장된 선택값을 위해 열쇠는 유지한다. */
    'ui.header.fold': '머리 접기 — 제목과 테마를 숨긴다',
    'ui.header.unfold': '머리 펼치기',
    'home.patch': '패치 기록',
    'home.patch.open': '패치 기록 보기',
    'home.patch.close': '닫기',
    'home.patch.note': '두 세션이 무엇을 왜 고쳤나. 새 것이 위.',
    'home.patch.loading': '읽는 중',
    'home.patch.none': '아직 적힌 것이 없다',
    'home.patch.fail': '패치 기록을 읽지 못했다 — docs/PATCH.md',
    'ui.theme': '테마',
    'ui.density': '화면 밀도',
    'ui.density.compact': '촘촘하게',
    'ui.density.relaxed': '여유롭게',
    'theme.midnight': '야간 도감', 'theme.daylight': '포켓몬 연구소', 'theme.blossom': '페어리 가든',
    'theme.moss': '상록숲', 'theme.plum': '고스트 타워', 'theme.sand': '피카츄 옐로',
    'theme.deep': '블루오션', 'theme.ember': '불꽃 체육관',

    /* 새 판 알림 */
    'fresh.notice': '새 판이 나왔습니다. 하던 것을 마치고 눌러 주세요.',
    'fresh.reload': '갈아타기',
    'fresh.close': '닫기',
    'fresh.stamp': '판',

    /* 카드가 들고 있는 값 — 이름표는 data/label.json 에서 온다.
       여기 있는 것은 그 값에 붙는 제목이다 */
    'card.no': '도감 번호',
    'card.size': '크기',
    'card.stats': '종족값',
    'card.total': '합계',
    'card.egg': '알그룹',
    'card.color': '색',
    'card.shape': '모양',
    'card.gen': '{n}세대',
    'card.evo': '진화',
    'card.evo.from': '이전',
    'card.evo.to': '다음',
    'card.text': '도감 설명',
    'card.height': '{n}m',
    'card.weight': '{n}kg',
    'card.rare.legendary': '전설',
    'card.rare.mythical': '환상',

    /* 화면 사이 오가기 */
    'nav.index': '연구소',
    'nav.dex': '도감',
    'nav.prompt': '프롬프트',
    'nav.battle': '전투',
    'nav.run': '런',
    'run.title': '일곱 판',
    'home.run.code': '04 / RUN',
    'home.run.title': '일곱 판 달리기',
    'home.run.note': 'AI 여섯과 한 팩에서 드래프트하고, 그 여섯과 보스를 차례로 만난다. 덜 자란 카드를 키우면 더 세진다.',
    'run.new': '새 런',
    'run.seed': '씨앗 {n}',
    'run.stage': '{n} / {total} 판',
    'run.draft.title': '드래프트 {n} / {total} 바퀴',
    'run.draft.note': '일곱 자리가 한 팩에서 뱀 순서로 집는다. 내 차례에 남은 것 가운데 하나. 덜 자란 카드는 지금은 약하지만 런 안에서 진화할 때마다 예산에 보정이 붙어, 다 키우면 처음부터 완성형으로 집은 것보다 세다.',
    'run.draft.turn': '내 차례 — {left}장 남음',
    'run.draft.taken': '{seat} 가 집음',
    'run.seat.me': '나',
    'run.seat.ai': 'AI {n}',
    'run.reroll': '보급 요청 · {n} / {max}',
    'run.reroll.last': '마지막 바퀴 · 보급 불가',
    'run.rivals': '같은 팩에서 뽑은 여섯 — 약한 순서로 만난다',
    'run.rival.line': '{seat}: {names}',
    'run.foes.seat': '{seat} · {n}번 자람',
    'run.foes.boss': '보스',
    'run.grown': '런에서 {n}번 진화 · 예산 +{bonus}',
    'run.nature.title': '성격 — 어느 폼이 몸에 맞나',
    'run.nature.note': '셋에게 하나씩. 두 능력치가 오르고 둘이 내린다. 그 폼으로 판에 서고, 맡길 때 운용이 그 폼을 일하는 폼으로 삼는다. 갈아 입기는 그대로 된다. 진화해도 성격은 남는다.',
    'run.nature.heavy': '중장형',
    'run.nature.mobility': '고기동형',
    'run.nature.light': '경장형',
    'run.nature.heavy.note': '방어·특방 +20% · 공격·스피드 −20%. 받아낸다',
    'run.nature.mobility.note': '공격·스피드 +20% · 방어·특방 −20%. 피하고 따라붙는다',
    'run.nature.light.note': 'HP·특공 +20% · 공격·방어 −20%. 되돌린다. 시작만 경장, 일하는 폼은 능력치대로',
    'run.nature.fit': '몸에 맞는다',
    'run.nature.go': '이 성격으로 간다',
    'run.od.title': '{name} — 오버라이드가 찼다',
    'run.od.note': '지금 터뜨리면 다음 박자에 ×1.8 로 때리고 대상을 고른다. 아끼면 Drive 가 그대로 남는다. 맡긴 판은 이 순간에만 멈춘다.',
    'run.od.fire': '터뜨린다',
    'run.od.hold': '아낀다',
    'run.od.target': '대상',
    'run.fight.running': '굴리는 중 — 오버라이드가 차면 멈춘다',
    'run.growth.2': '두 번 더 큰다',
    'run.growth.1': '한 번 더 큰다',
    'run.growth.0': '다 컸다',
    'run.pick': '이 카드로',
    'run.roster': '로스터',
    'run.foes': '상대',
    'run.foes.note': '{policy}',
    'run.fight.auto': '맡기고 끝까지',
    'run.fight.manual': '직접 조종',
    'run.fight.go': '싸운다',
    'run.fight.won': '이겼다 · {beats}박자',
    'run.fight.lost': '졌다 · {beats}박자',
    'run.down': '쓰러짐',
    'run.reward.title': '보상 — 하나만',
    'run.reward.evolve': '진화',
    'run.reward.evolve.note': '{list} — 예산이 한 단계 오르고 체력이 찬다',
    'run.reward.heal': '회복',
    'run.reward.heal.note': '전부 절반 회복. 쓰러진 것은 절반으로 되살아난다',
    'run.reward.step': '{from} → {to}',
    'run.won.title': '일곱 판을 다 이겼다',
    'run.lost.title': '{n}판에서 졌다',
    'run.end.note': '판마다 상대 · 박자 수',
    'run.end.line': '{stage}판 {result} — {foes} · {beats}박자',
    'run.win': '승',
    'run.lose': '패',
    'run.again': '다시 — 새 씨앗으로',
    'run.hp': '체력 {n}%',
    'run.help': '나와 AI 여섯이 한 팩에서 세 장씩 뽑는다. 그 여섯을 약한 순서로 차례로 만나고, 그들도 판마다 자라 있다. 일곱째는 보스. 체력은 다음 판으로 이어지고, 판 사이에 진화(전부 한 단계, 체력이 찬다) 아니면 회복(절반) 을 고른다.',
    'battle.title': '전투 시험장',
    'home.battle.code': '03 / BATTLE',
    'home.battle.title': '전투 굴려 보기',
    'home.battle.note': '세 마리씩 골라 규칙대로 굴린다. 박자마다 폼과 Heat, Drive 가 어떻게 움직이는지 본다.',
    'battle.side.a': '아군',
    'battle.side.b': '상대',
    'battle.slot': '카드 이름',
    'battle.policy': '운용',
    'battle.policy.managed': '운용 — 맞고 나서 식힌다, 찼으면 연다',
    'battle.policy.stay:light': '경장에 눌러앉기',
    'battle.policy.stay:heavy': '중장에 눌러앉기',
    'battle.policy.stay:mobility': '고기동에 눌러앉기',
    'battle.policy.burn': '중장 + 열 수 있으면 연다',
    'battle.seed': '씨앗',
    'battle.run': '한 판',
    'battle.many': '100판',
    'battle.running': '굴리는 중…',
    'battle.unknown': '{name} — 없는 카드',
    'battle.winner': '{side} 승 · {beats}박자',
    'battle.draw': '무승부 · {beats}박자',
    'battle.rate': '아군 {a}% · 상대 {b}% · 무승부 {d}% — {n}판, 양쪽을 바꿔 두 번씩',
    'battle.beat': '박자 {n} / {total}',
    'battle.first': '처음',
    'battle.prev': '앞 박자',
    'battle.next': '다음 박자',
    'battle.last': '끝',
    'battle.open': '열림',
    'battle.forced': '강제 개방',
    'battle.down': '쓰러짐',
    'battle.events': '이 박자에 일어난 것',
    'battle.ev.attack': '{who} 공격',
    'battle.ev.hit': '{who} → {to} {dmg}{guard}{untargeted}',
    'battle.ev.guard': ' (중장이 받아냄)',
    'battle.ev.untargeted': ' (대상 못 고름)',
    'battle.ev.vent': '{who} 강제 방출',
    'battle.ev.evade': '{who} 피함 · Heat {heatBefore}→{heat}',
    'battle.ev.switch': '{who} → {form} · Heat {heatBefore}→{heat}',
    'battle.ev.open': '{who} 개방',
    'battle.ev.forced-open': '{who} 과열 — 강제 개방',
    'battle.ev.open-end': '{who} 개방 끝',
    'battle.ev.skip': '{who} 행동을 잃음',
    'battle.ev.extra': '{who} 연속행동',
    'battle.ev.down': '{who} 쓰러짐',
    'battle.play': '아군을 직접 조종한다',
    'battle.start': '시작',
    'battle.step': '박자 굴리기',
    'battle.plan': '이 박자에 할 것 — 안 고른 아군은 운용 규칙이 맡는다',
    'battle.cmd.auto': '맡김',
    'battle.cmd.attack': '공격',
    'battle.cmd.open': '개방',
    'battle.cmd.target': '대상',
    'battle.cmd.any': '규칙대로',
    'battle.cmd.extra': '연속행동',
    'battle.over': '끝 — {result}',
    'battle.help': '박자 사이에 멈춘다. 아군마다 할 것을 고르고 굴리면 한 박자가 지나간다. 전환은 잠금이 풀려야, 개방은 Drive 가 차야 고를 수 있다.',
    'battle.note': '규칙은 lib/battle.js 그대로다. docs/GAME_CONCEPT.md 의 "굴려 본 것" 이 이 판에서 나온 숫자다. 이름을 바꾸면 도감의 아무 카드나 세울 수 있다.',

    /* 도감 */
    'dex.compare': '나란히 보기',
    'dex.overdrive.legacy': '기존 폭주 이미지 · 기준 장갑 미지정',
    "dex.view.small": "작게 보기",
    "dex.view.normal": "기본 크기",
    "dex.filter.title": "검색 조건 · 목록 이미지",
    "dex.filter.style": "화풍",
    "dex.filter.gen": "세대",
    "dex.filter.type": "타입",
    "dex.filter.form": "장갑 폼",
    "dex.filter.cut": "목록 이미지",
    "dex.filter.all": "전체",
    "dex.filter.reset": "초기화",
    "dex.filter.search": "이름 · 영문명 · 도감번호 검색",
    "dex.filter.note": "타입은 두 속성 모두 검색해요. 화풍·폼·컷을 고르면 해당 이미지가 등록된 결과만 표시해요.",
    "dex.filter.formNote": "폼은 대표 이미지·전체 컷·폼 초상·액션컷에 적용해요.",
    "dex.filter.empty": "선택한 조건에 맞는 결과가 없어요. 검색 조건을 바꿔 보세요.",
    "dex.filter.count": "{cards}종 · {images}장",
    "dex.cut.auto": "대표 이미지",
    "dex.cut.all": "전체 컷",
    "dex.cut.base": "기본 초상 (구형)",
    "dex.cut.portrait": "폼 초상",
    "dex.cut.action": "액션컷",
    "dex.cut.casual": "일상컷",
    "dex.cut.extra": "특별컷",
    "dex.style.unknown": "화풍 미분류",
    "dex.cut.number": "{cut} {n}",
    "dex.form.legacy": "폭주 (구형)",
    "dex.selected": "선택한 이미지",
    'dex.style': '화풍',
    'dex.action': '연출컷',
    'dex.casual': '일상컷',
    'dex.layers': '겹',
    'ui.back': '목록으로',

    /* 그림 */
    'art.none': '그림 없음',
    'art.missing': '아직 안 만든 것',
    'art.count': '{n}장',
    'art.form.done': '폼 {done} / {all}',
    'art.form.left': '남은 폼 {n}',
  };

  var missing = {};
  function W(key, vars) {
    var s = WORDS[key];
    if (s === undefined) {
      /* 조용히 빈칸으로 두면 화면에서만 티가 나고 원인을 못 찾는다 */
      if (!missing[key]) { missing[key] = 1; console.warn('낱말 표에 없는 열쇠: ' + key); }
      return key;
    }
    if (!vars) return s;
    return s.replace(/\{(\w+)\}/g, function (m, k) {
      return vars[k] === undefined ? m : String(vars[k]);
    });
  }

  /* 표를 통째로 갈아 끼울 때(다른 주제로 시험할 때) 쓴다 */
  function load(table) { for (var k in table) WORDS[k] = table[k]; }

  root.AtelierWords = { W: W, load: load, table: WORDS,
    missing: function () { return Object.keys(missing); } };
  root.W = W;   /* 화면에서 짧게 부르라고 */
})(window);
